### ISSUE TITLE
Frame-rate

### ISSUE THREAD

**Issue by pratishdesai** [sturmen/SpatialMediaKit#5]
Hi,

Encoder output shows variable frame-rate on media-info.

Can you please update to provide fix frame-rate output?

Thanks.

**Comment by austinarchibald** [comment]
+1 for this. It should match the framerate of the inputs, which for me are both fixed to 23.976. Also, would like a `-b` setting for specific bitrate rather than a subjective `-q` setting.

**Comment by pratishdesai** [comment]
in Media-info, frame-rate-mode is still **variable**. Please set it to **constant** frame-rate-mode with explicit framerate info. thanks.

**Comment by sturmen** [comment]
Hello @pratishdesai,

Please try again with `0.0.7` or newer. Please also make sure your source material itself has a constant framerate. I have validated this in MediaInfo myself with input from a QooCam EGO:

<img width="320" alt="Screenshot 2024-03-04 at 9 59 41 AM" src="https://github.com/sturmen/SpatialMediaKit/assets/169858/5b16b8b6-d756-489f-be59-e5c92c0cdfc3">

Thanks.

**Comment by pratishdesai** [comment]
Hi,

 Thanks for reply. 

For some reasons, In my case **FrameRateMode** is changed to **Variable**.
I checked the source code and I noticed that **Framerate** is matching to source **framerate**. But, looks like AV engine is changing the mode internally. Is it possible to explicitly fix the **FrameRateMode**?

Thanks.
