### ISSUE TITLE
Does this only run on Apple Silicon chips or should it be working fine on MACs with Intel chips as well?

### ISSUE THREAD

**Issue by sandeep-sm** [sturmen/SpatialMediaKit#9]
Hi,

This is an amazing work, especially because of its FOSS nature. 

I tried running it on a Mac with Intel Core i7, but received this output: 
"-bash: /usr/local/bin/spatial-media-kit-tool: Bad CPU type in executable"

I don't have access to a silicon chip Mac, but will try finding one and running on it. In the meantime, if you are aware of such a requirement and would be able to respond, it would be great. 

Thank you.

**Comment by cbusillo** [comment]
I believe this only runs on Apple Silicon.  The framework that is used is AS only.
